### ISSUE TITLE
Specification task list

### ISSUE THREAD

**Issue by pahans** [pahans/scissors-rock-paper#1]
# Test task specification:
Your test task is to create a React app, using Typescript with strict typing. 
The app is a scissors, rock, paper game, with the ability to bet on the winning position.

## Specifications
- [x] Player starts with a balance of 5000.
- [x] Each bet should be 500 (player can place several bets on any position: 500, 1000,
1500 etc)
- [x] Player can not bet more than 2 positions per one game
- [x] Winning rate for bet on 1 position is 14
- [x] Winning rate for bet on 2 positions is 3

## Requirements
- [x] There should be three betting positions, rock, paper, scissors.
- [x] Player can bet on rock, paper, or scissors, but not on all three at the same time.
- [x] The bet is reduced from the balance.
- [x] When betting done button is clicked, the computer runs a random paper, scissors,
rock match.
- [x] Player choice should be compared to computers choice and only one bet can win –
every tie counts as loss
- [x] If player bets on one of them and wins, the return is 14 times the bet.
- [x] If player bets on two of them and wins the return is 3 times the bet.
- [x] Loss bets are not returned to player
- [x] Bets with tie result are returned to player
- [x] After round ends the return adds to the balance
- [x] Player cannot bet if player has less balance than available for bet.

NB please keep in mind that Title ROCK vs PAPER on the second screen means “computer choice ROCK versus player choice PAPER” — not ROCK bet vs PAPER bet.

## Acceptance criteria
Every point of task should be implemented

### Junior level
In general implementing every point is enough for junior. Optionally we pay attention to such things as concistency, variable naming, files and folders structure. 

### Middle level
We pay attention to everything mentioned for Junior (optional part is mandatory for middle). Additionally we check UX and compare UI with mockups more thorough and we expect following clean code principles

### Senior level
We pay attention to everything mentioned for middle. Additionally we expect code to be flexible and maintainable. Changing of requirements should not lead to rewriting half of application. Changing of specifications should cause minimal changes.
